namespace Microsoft.Win32
{
    using System;

    public enum DWMWINDOWATTRIBUTE
    {
        DWMWA_ALLOW_NCPAINT = 4,
        DWMWA_CAPTION_BUTTON_BOUNDS = 5,
        DWMWA_FLIP3D_POLICY = 8,
        DWMWA_FORCE_ICONIC_REPRESENTATION = 7,
        DWMWA_NCRENDERING_ENABLED = 1,
        DWMWA_NCRENDERING_POLICY = 2,
        DWMWA_NONCLIENT_RTL_LAYOUT = 6,
        DWMWA_TRANSITIONS_FORCEDISABLED = 3
    }
}

