namespace Microsoft.Win32
{
    using System;

    [Flags]
    public enum FILE_SYSTEM_FLAGS : uint
    {
        FILE_CASE_PRESERVED_NAMES = 2,
        FILE_CASE_SENSITIVE_SEARCH = 1,
        FILE_FILE_COMPRESSION = 0x10,
        FILE_NAMED_STREAMS = 0x40000,
        FILE_PERSISTENT_ACLS = 8,
        FILE_READ_ONLY_VOLUME = 0x80000,
        FILE_SEQUENTIAL_WRITE_ONCE = 0x100000,
        FILE_SUPPORTS_ENCRYPTION = 0x20000,
        FILE_SUPPORTS_OBJECT_IDS = 0x10000,
        FILE_SUPPORTS_REMOTE_STORAGE = 0x100,
        FILE_SUPPORTS_REPARSE_POINTS = 0x80,
        FILE_SUPPORTS_SPARSE_FILES = 0x40,
        FILE_SUPPORTS_TRANSACTIONS = 0x200000,
        FILE_UNICODE_ON_DISK = 4,
        FILE_VOLUME_IS_COMPRESSED = 0x8000,
        FILE_VOLUME_QUOTAS = 0x20
    }
}

